// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Hehe: typeof import('./src/components/Hehe.vue')['default']
    Hihi: typeof import('./src/components/Hihi.vue')['default']
    ModalContent: typeof import('./src/components/ModalContent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
